### ISSUE TITLE
I need to..

### ISSUE THREAD

**Issue by sigmanotskid** [0Zayn/Ballistic#1]
please tel me how find encryptions!! I got some from lgcdebug.cpp but idk where's the rest!!!

**Comment by ethanmcdonagh** [comment]
Hi savage

**Comment by AnaIytics** [comment]
Did u check '

**Comment by Savage3991** [comment]
> Hi savage

thats not me 😭

**Comment by sigmanotskid** [comment]
> Hi savage

I'm sigmanotskid@proton.me

**Comment by 0Zayn** [comment]
> please tel me how find encryptions!! I got some from lgcdebug.cpp but idk where's the rest!!!

Hello, xspy
