### ISSUE TITLE
Im gonna touch you if you dont unpost this NOW

### ISSUE THREAD

**Issue by iusethisLol** [0Zayn/Ballistic#2]
Stop spreading free sources, the skidsploits will spread 😡

**Comment by nhisoka** [comment]
frrrrrrrrrrrrrrrrrrrrrrrrr

**Comment by Savage3991** [comment]
> frrrrrrrrrrrrrrrrrrrrrrrrr

#1 paster detected

**Comment by nhisoka** [comment]
shut up skid 💀

**Comment by Savage3991** [comment]
> shut up skid 💀

🗣️ proof that im a skid
